import { z } from "zod";

export const userSchema = z.object({
  id: z.string(),
  profile_id: z.string(),
  aud: z.null(),
  confirmed_at: z.null(),
  confirmation_token: z.null(),
  confirmation_sent_at: z.null(),
  role: z.string(),
  is_sso_user: z.boolean(),
  is_super_admin: z.boolean(),
  email: z.string(),
  email_confirmed_at: z.null(),
  email_change_token_new: z.null(),
  email_change: z.null(),
  email_change_sent_at: z.null(),
  email_change_token_current: z.string(),
  email_change_confirm_status: z.boolean(),
  encrypted_password: z.null(),
  salt: z.null(),
  recovery_token: z.null(),
  recovery_sent_at: z.null(),
  phone: z.null(),
  phone_confirmed_at: z.null(),
  phone_change: z.string(),
  phone_change_token: z.null(),
  phone_change_sent_at: z.null(),
  reauthentication_token: z.null(),
  reauthentication_sent_at: z.null(),
  banned_at: z.null(),
  banned_until: z.null(),
  invited_at: z.null(),
  created_at: z.string(),
  updated_at: z.string(),
  deleted_at: z.null(),
});
export type User = z.infer<typeof userSchema>;
